# Dependencies
markdown:            kramdown

redcarpet:
  extensions: ["tables", "fenced_code_block"]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

exclude:      ["*.Rmd"]


# Setup
title:               Real-Time Analytics
tagline:             'Lectures for SGH students'
description:         'Real-Time Analytics'
url:                 https://sebkaz.github.io/RealTimeEN
baseurl:             "/RealTimeEN"             
paginate:            5

# About/contact
author:
  name:              Sebastian ZajÄ…c
  url:               https://sebastianzajac.pl
  email:             sebastian.zajac@sgh.waw.pl

# Custom vars
version:             1.0.0
